include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - one

build:
  stage: one
  timeout: 8 hours
  extends: .kokkuri:build-image
  variables:
    BUILD_CONFIG: dockerfile
    BUILD_VARIANT: ""