include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - publish-build

publish-build:
  stage: publish-build
  extends: .kokkuri:build-and-publish-image
  variables:
    timeout: 8 hours
    BUILD_CONFIG: dockerfile
    BUILD_VARIANT: ""
    KOKKURI_REGISTRY_PUBLIC: $DOCKER_REGISTRY
    KOKKURI_REGISTRY_INTERNAL: $DOCKER_REGISTRY
    KOKKURI_REGISTRY_USER: $QUAY_USER
    KOKKURI_REGISTRY_PASSWORD: $QUAY_TOKEN
    PUBLISH_IMAGE_NAME: $REGISTRY_IMAGE
    PUBLISH_IMAGE_TAG: latest
