include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - one
  - two

build:
  stage: one
  timeout: 8 hours
  extends: .kokkuri:build-image
  variables:
    BUILD_CONFIG: dockerfile
    BUILD_VARIANT: ""
    CI_COMMIT_TAG: latest

push:
  stage: two
  variables:
      IMAGE_TAG: $REGISTRY_IMAGE:latest
  script:
      echo "$QUAY_TOKEN" | docker login $DOCKER_REGISTRY -u $QUAY_USER --password-stdin
      docker push $IMAGE_TAG
